- name: Backup origin repos
  shell: for repo in $(ls /etc/yum.repos.d/*.repo);do mv /etc/yum.repos.d/$repo /etc/yum.repos.d/${repo}.bak;done

- name: Create proxy repo 
  template:
    src: templates/CentOS-Base-Proxy.repo.j2
    dest: /etc/yum.repos.d/CentOS-Base-Proxy.repo 

